FROM ubuntu:14.04
MAINTAINER Andrii Ivanskiy andrii@ivanskiy.com
RUN  apt-get update && apt-get -y install wget
RUN touch /home/readme.md
RUN echo 'My container to push on GitHub and build on DockerHub' \
 >/home/readme.md