#######################################################
# Dockerfile to build a LOG Volume for Apache2 Service
#######################################################
FROM busybox:latest
MAINTAINER Andrii Ivanskiy andrii@ivanskiy.com
#Create data volume for apache logs
VOLUME /var/log/apache2
CMD ["/bin/true"]